# Generated by Django 5.2.10 on 2026-01-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('PESSOA', 'Pessoa'), ('EMPRESA', 'Empresa')], default='PESSOA', max_length=10, verbose_name='Tipo de usuário'),
        ),
    ]
